### ISSUE TITLE
unknown dialyzer warning option: no_underspecs

### ISSUE THREAD

**Issue by python36** [okeuday/quickrand#7]
Hi. I have a compilation error:
```
_build/default/lib/quickrand/src/quickrand_hash.erl:80: unknown dialyzer warning option: no_underspecs
```
I have Erlang/OTP 24 and Dialyzer version v4.3 but the argument `no_underspecs` has been supported since [version 4.4](http://erlang.org/doc/apps/dialyzer/notes.html).

```
1> erlang:system_info(otp_release).
"24"
...
$> dialyzer --version
Dialyzer version v4.3
```

**Comment by okeuday** [comment]
@python36 That is a dialyzer error, not a compilation error, right?  The `quickrand_hash` module is turning off that warning when it is compiled with Erlang/OTP 24 and is expecting the dialyzer included with Erlang/OTP 24 to be used which is v4.4 .  So, if you use the new dialyzer you shouldn't have any problems.
